[global]
# Global configuration for Streamlit

# Development mode
developmentMode = false

[server]
# Server configuration
port = 8501
address = "0.0.0.0"
baseUrlPath = ""
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 10
maxMessageSize = 200
enableWebsocketCompression = false

[browser]
# Browser configuration
gatherUsageStats = false

[theme]
# LoadTester professional theme
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
# Client configuration
showErrorDetails = false
toolbarMode = "minimal"

[runner]
# Runner configuration
magicEnabled = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = true

[logger]
# Logging configuration
level = "info"
enableRich = false

